export const WEDDING_DATE = new Date("2026-06-06T14:30:00");

export const WEDDING_INFO = {
  groomName: "김우혁",
  brideName: "노현정",
  groomNameEn: "Kim Woo-hyeok",
  brideNameEn: "Noh hyun-jeong",
  date: WEDDING_DATE,
  dateStr: "2026년 6월 6일 토요일",
  timeStr: "오후 2시 30분",
  venue: "더 링크 서울",
  venueDetail: "7층 화이트홀",
  address: "서울 구로구 경인로 610",

  groom: {
    name: "김우혁",
    phone: process.env.NEXT_PUBLIC_GROOM_PHONE ?? "",
    fatherName: "김황중",
    fatherPhone: process.env.NEXT_PUBLIC_GROOM_FATHER_PHONE ?? "",
    fatherBank: process.env.NEXT_PUBLIC_GROOM_FATHER_BANK ?? "",
    fatherAccount: process.env.NEXT_PUBLIC_GROOM_FATHER_ACCOUNT ?? "",
    motherName: "성정선",
    motherPhone: process.env.NEXT_PUBLIC_GROOM_MOTHER_PHONE ?? "",
    motherBank: process.env.NEXT_PUBLIC_GROOM_MOTHER_BANK ?? "",
    motherAccount: process.env.NEXT_PUBLIC_GROOM_MOTHER_ACCOUNT ?? "",
    bank: process.env.NEXT_PUBLIC_GROOM_BANK ?? "",
    account: process.env.NEXT_PUBLIC_GROOM_ACCOUNT ?? "",
    holder: "김우혁",
  },
  bride: {
    name: "노현정",
    phone: process.env.NEXT_PUBLIC_BRIDE_PHONE ?? "",
    fatherName: "노태훈",
    fatherPhone: process.env.NEXT_PUBLIC_BRIDE_FATHER_PHONE ?? "",
    fatherBank: process.env.NEXT_PUBLIC_BRIDE_FATHER_BANK ?? "",
    fatherAccount: process.env.NEXT_PUBLIC_BRIDE_FATHER_ACCOUNT ?? "",
    motherName: "은진경",
    motherPhone: process.env.NEXT_PUBLIC_BRIDE_MOTHER_PHONE ?? "",
    motherBank: process.env.NEXT_PUBLIC_BRIDE_MOTHER_BANK ?? "",
    motherAccount: process.env.NEXT_PUBLIC_BRIDE_MOTHER_ACCOUNT ?? "",
    bank: process.env.NEXT_PUBLIC_BRIDE_BANK ?? "",
    account: process.env.NEXT_PUBLIC_BRIDE_ACCOUNT ?? "",
    holder: "노현정",
  },
};

const BLOB = process.env.NEXT_PUBLIC_BLOB_BASE_URL;

export const PHOTOS = [
  `${BLOB}/main.webp`,
  `${BLOB}/1.webp`,
  `${BLOB}/3.webp`,
  `${BLOB}/4.webp`,
  `${BLOB}/5.webp`,
  `${BLOB}/6.webp`,
  `${BLOB}/7.webp`,
  `${BLOB}/8.webp`,
  `${BLOB}/10.webp`,
  `${BLOB}/11.webp`,
  `${BLOB}/12.webp`,
  `${BLOB}/13.webp`,
  `${BLOB}/14.webp`,
  `${BLOB}/15.webp`,
  `${BLOB}/17.webp`,
];
